# This template is managed by Pushpath

VAGRANTFILE_API_VERSION = "2"

manifests_path = "manifests/pushpath-plugin-lamp"
manifests_file = "init.pp"
shell_file = "init.sh"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.box = "{{=tpl.config_vm_box}}"
    config.vm.box_url = "{{=tpl.config_vm_box_url}}"
    config.vm.synced_folder "{{=tpl.config_vm_synced_folder_src}}", "{{=tpl.config_vm_synced_folder_target}}"

    # Networking
    config.vm.define :net do |net|
        net.vm.network :{{=tpl.network_type}}, ip: "{{=tpl.network_ip}}"
    end

    # VM provider
    config.vm.provider :{{=tpl.provider_type}} do |vm|
       vm.name = "{{=tpl.provider_name}}"
    end

    # Shell provisioning
    config.vm.provision "shell", path: "#{manifests_path}/#{shell_file}"

    # Puppet provisioning
    config.vm.provision :puppet do |puppet|
        puppet.manifests_path = "#{manifests_path}"
        puppet.manifest_file  = "#{manifests_file}"
    end
end